-- Criado por Franky Weber Faust 15/03/2011
-- http://loredata.com.br
-- Lista o espaço utilizado pela FRA.
set pages 200 lin 200
SELECT FILE_TYPE,
       PERCENT_SPACE_USED,
       PERCENT_SPACE_RECLAIMABLE,
       NUMBER_OF_FILES,
       CON_ID
  FROM V$RECOVERY_AREA_USAGE;

/*SELECT FILE_TYPE,
       PERCENT_SPACE_USED,
       PERCENT_SPACE_RECLAIMABLE,
       NUMBER_OF_FILES,
       CON_ID
  FROM V$FLASH_RECOVERY_AREA;*/

COLUMN NAME FORMAT A70
SELECT V.Name,
       V.SPACE_LIMIT / 1024 / 1024 SPCLIM_MB,
       V.SPACE_USED / 1024 / 1024 SPCUSED_MB,
       V.SPACE_RECLAIMABLE / 1024 / 1024 SPCREC_MB,
       V.NUMBER_OF_FILES,
       V.CON_ID
  FROM V$RECOVERY_FILE_DEST V;
